# Используем официальный образ OpenJDK 22
FROM openjdk:22-jdk

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файл сборки Maven и зависимостей
COPY pom.xml ./
COPY src ./src

# Скачиваем зависимости и собираем проект
RUN ./mvnw package -DskipTests

# Указываем порт, который будет использовать приложение
EXPOSE 8080

# Команда для запуска приложения
CMD ["java", "-jar", "target/sys-0.0.1-SNAPSHOT.jar"]
